Reference https://mxnet.incubator.apache.org/api/python/docs/api/ndarray/index.html 

In [1]:
import sys
sys.path.append("/workspace/server")
import warnings

from thera.python.mxnet import mxnet as mx
warnings.filterwarnings('ignore')

import random
import numpy as np
import mxnet as mx
from mxnet import gluon
import gluonnlp as nlp
# https://gluon-nlp.mxnet.io/master/examples/word_embedding/word_embedding.html
import re

In [2]:
import mxnet as mx
# create a 1-dimensional array with a python list
a = mx.nd.array([1,2,3])
# create a 2-dimensional array with a nested python list
b = mx.nd.array([[1,2,3], [2,3,4]])
{'a.shape':a.shape, 'b.shape':b.shape}

{'a.shape': (3,), 'b.shape': (2, 3)}

mxnet.ndarray is similar to numpy.ndarray in some aspects. But the differences are not negligible. For instance:

    mxnet.ndarray.NDArray.T does real data transpose to return new a copied array, instead of returning a view of the input array.

    mxnet.ndarray.dot performs dot product between the last axis of the first input array and the first axis of the second input, while numpy.dot uses the second last axis of the input array.

In addition, mxnet.ndarray.NDArray supports GPU computation and various neural network layers.


Note

ndarray provides almost the same routines as symbol. Most routines between these two packages share the source code. But ndarray differs from symbol in few aspects:

    ndarray adopts imperative programming, namely sentences are executed step-by-step so that the results can be obtained immediately whereas symbol adopts declarative programming.

    Most binary operators in ndarray such as + and > have broadcasting enabled by default.



In [4]:
np.dot([1,2,3],[4,5,6])

32

In [31]:
a_mx = mx.nd.array([1,2,3])
b_mx = mx.nd.array([4,5,6])
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])

In [32]:
a_mx * b_mx


[ 4. 10. 18.]
<NDArray 3 @cpu(0)>

In [33]:
a_np * b_np

array([ 4, 10, 18])

In [34]:
mx.ndarray.dot(a_mx, b_mx)

ValueError: not enough values to unpack (expected 2, got 1)

In [17]:
np.dot(a_np, b_np)

32

In [36]:
a_mx = mx.nd.array([[1,2,3], [4,5,6]])
a_np = np.array([[1,2,3], [4,5,6]])
b_np = np.array([[4,5], [6,7], [8,9]])
b_mx = mx.nd.array([[4,5], [6, 7],[8,9]])

In [37]:
np.dot(a_np, b_np)

array([[ 40,  46],
       [ 94, 109]])

In [39]:
j, i = mx.ndarray.dot(a_mx, b_mx)
k = mx.ndarray.dot(a_mx, b_mx)
print(" j {} i {} k {}".format(j, i, k))

 j 
[40. 46.]
<NDArray 2 @cpu(0)> i 
[ 94. 109.]
<NDArray 2 @cpu(0)> k 
[[ 40.  46.]
 [ 94. 109.]]
<NDArray 2x2 @cpu(0)>
